repository: dynamsoft-docs/document-normalizer-docs-mobile
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs-mobile/blob/main
docFullPath: https://www.dynamsoft.com/document-normalizer/docs/mobile/
firstLevelUrl: /document-normalizer/docs/mobile
docHomePage: /document-normalizer/docs/core/introduction/

parameters: /document-normalizer/docs/core/parameters/

dcv_ios: /capture-vision/docs/mobile/programming/ios/
dcv_ios_api: /capture-vision/docs/mobile/programming/ios/api-reference/

dcv_android: /capture-vision/docs/mobile/programming/android/
dcv_android_api: /capture-vision/docs/mobile/programming/android/api-reference/

dcv_introduction: /capture-vision/docs/core/introduction/

dce_android: /camera-enhancer/docs/mobile/programming/android/
dce_ios: /camera-enhancer/docs/mobile/programming/ios/

dcv_enums: /capture-vision/docs/core/enums/

ios: /document-normalizer/docs/mobile/programming/ios/
ios_api: /document-normalizer/docs/mobile/programming/ios/api-reference/
ios_release_notes: /document-normalizer/docs/mobile/programming/ios/release-notes/
ios_camera_enhancer: /document-normalizer/docs/mobile/programming/ios/api-reference/camera-enhancer/

android: /document-normalizer/docs/mobile/programming/android/
android_api: /document-normalizer/docs/mobile/programming/android/api-reference/
android_release_notes: /document-normalizer/docs/mobile/programming/android/release-notes/
android_camera_enhancer: /document-normalizer/docs/mobile/programming/android/api-reference/camera-enhancer/

xamarin: /document-normalizer/docs/mobile/programming/xamarin/
xamarin_api: /document-normalizer/docs/mobile/programming/xamarin/api-reference/
xamarin_release_notes: /document-normalizer/docs/mobile/programming/xamarin/release-notes/
xamarin_camera_enhancer: /document-normalizer/docs/mobile/programming/xamarin/api-reference/camera-enhancer/

enumerations: /document-normalizer/docs/mobile/programming/enumerations/

js: /document-normalizer/docs/web/programming/javascript/
cpp: /document-normalizer/docs/server/programming/cplusplus/

useVersionTree: true

assets: /document-normalizer/docs/mobile/assets/
edit_icon: /document-normalizer/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/docs/mobile/assets/img-icon/icon-sad.png

baseurl: "/document-normalizer/docs/mobile"

download: "/document-normalizer/downloads/"

plugins:
  - jemoji
  - jekyll-sitemap


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Android Edition" 
      docHomePage: "/document-normalizer/docs/mobile/programming/android/"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader iOS Edition" 
      docHomePage: "/document-normalizer/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "programming-old/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Android Edition" 
      docHomePage: "/document-normalizer/docs/mobile/programming/android/"
  - scope:
      path: "programming-old/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader iOS Edition" 
      docHomePage: "/document-normalizer/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
